apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: registry.cloud.okteto.net/ticketing-fiqrisr/micro-ticketing:tickets
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://fiqrisr:fiqri123@cluster0.kbazm.mongodb.net/tickets?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: tickets
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
